DEFAULT_IGNORE_DIRS = {
    # VCS
    ".git",
    ".svn",
    ".hg",
    # Keep
    "!.gitignore",
    "!.placeholder",
    "!.github",
    "!.gitlab-ci.yml",
    # Python
    "__pycache__",
    "venv",
    ".venv",
    "env",
    ".env",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    ".coverage",
    "build",
    "dist",
    # JS / Node
    "node_modules",
    "bower_components",
    ".parcel-cache",
    ".next",
    ".nuxt",
    ".turbo",
    "coverage",
    # Java / JVM
    "target",
    "out",
    "build",
    # C / C++ / Go
    "bin",
    "obj",
    ".gradle",
    ".idea",
    ".vscode",
    # OS / Editors
    ".DS_Store",
    "Thumbs.db",
    ".vs",
    ".classpath",
    ".project",
    ".settings",
    # Secrets
    "secret",
    "secrets",
    "secrets.*",
    "secret.*",
    # Containers
    ".docker",
    ".devcontainer",
    # Logs / Temp
    "logs",
    "tmp",
    "temp",
    ".cache",
    # Terraform
    ".terraform",
    "*.tfstate",
    "*.tfstate.*",
    "crash.log",
    "crash.*.log",
    "*.tfvars",
    "*.tfvars.json",
    "override.tf",
    "override.tf.json",
    "*_override.tf",
    "*_override.tf.json",
    ".terraform.tfstate.lock.info",
    ".terraformrc",
    "terraform.rc",
    # Ansible
    "ansible/roles/*",
    "!ansible/roles/project-*",
    "!ansible/roles/README.md",
    # Misc
    "*.log",
    "*.py[co]",
    "*~",
    "*.swp",
    "*.retry",
    "sandbox",
    "inventory.ini",
}
